import type {
  Agent, ThreatEvent, GovernanceAction, AuditEvent,
  DashboardMetrics, CertificationJob, MasterAgentDecision,
} from './types';

// ─── Dashboard Metrics ──────────────────────────────────────────────────────
export const dashboardMetrics: DashboardMetrics = {
  registeredAgents: 2847,
  certifiedAgents: 1923,
  pendingReviews: 134,
  threatsBlocked: 48291,
  permissionViolations: 7823,
  activeSessions: 3401,
  trustIndex: 94.7,
  governanceScore: 97.2,
  platformHealth: 99.8,
  agentRevenue: 4820000,
};

// ─── Agents ─────────────────────────────────────────────────────────────────
export const agents: Agent[] = [
  {
    id: 'agent-001',
    name: 'Disaster Intelligence Agent',
    slug: 'disaster',
    description: 'Global disaster monitoring, prediction, and emergency response coordination.',
    longDescription: 'A real-time global disaster intelligence system that continuously monitors earthquakes, floods, wildfires, cyclones, and other catastrophic events. Integrates with global sensor networks and satellite imagery to provide actionable intelligence for emergency responders.',
    developer: 'SentinelOS Labs',
    developerAvatar: 'SL',
    version: '3.2.1',
    category: 'disaster_intelligence',
    trustScore: 98.4,
    governanceScore: 97.8,
    certificationLevel: 'sovereign',
    status: 'active',
    riskLevel: 'low',
    requiredPermissions: [
      { id: 'p1', name: 'External API Access', type: 'external_api', scope: 'read', risk: 'low', status: 'granted' },
      { id: 'p2', name: 'Network Access', type: 'network', scope: 'read', risk: 'low', status: 'granted' },
    ],
    pricing: { model: 'subscription', monthly: 299, annual: 2990, currency: 'USD' },
    ratings: 4.9,
    reviewCount: 1847,
    subscribers: 34201,
    monthlyActiveUsers: 28900,
    tags: ['disaster', 'emergency', 'gis', 'monitoring', 'prediction'],
    capabilities: ['Real-time disaster tracking', 'GIS heat maps', 'Emergency response coordination', 'Historical analytics', 'Satellite integration'],
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2026-05-20T00:00:00Z',
    lastAuditAt: '2026-06-01T00:00:00Z',
    icon: '🌐',
    color: '#0EA5E9',
  },
  {
    id: 'agent-002',
    name: 'Cyber Defense Agent',
    slug: 'cyber',
    description: 'Advanced threat detection, network analysis, and incident response automation.',
    longDescription: 'A mission-critical cybersecurity agent that detects, analyzes, and responds to threats in real time. Uses advanced behavioral analysis, anomaly detection, and attack simulation to keep your infrastructure secure.',
    developer: 'SentinelOS Labs',
    developerAvatar: 'SL',
    version: '5.1.0',
    category: 'cyber_defense',
    trustScore: 99.1,
    governanceScore: 98.9,
    certificationLevel: 'sovereign',
    status: 'active',
    riskLevel: 'low',
    requiredPermissions: [
      { id: 'p3', name: 'Network Monitoring', type: 'network', scope: 'read/write', risk: 'medium', status: 'granted' },
      { id: 'p4', name: 'File System Read', type: 'files', scope: 'read', risk: 'low', status: 'granted' },
      { id: 'p5', name: 'External API', type: 'external_api', scope: 'read', risk: 'low', status: 'granted' },
    ],
    pricing: { model: 'enterprise', monthly: 999, annual: 9990, currency: 'USD' },
    ratings: 4.95,
    reviewCount: 2341,
    subscribers: 18400,
    monthlyActiveUsers: 15200,
    tags: ['security', 'cyber', 'threat-detection', 'incident-response', 'defense'],
    capabilities: ['Threat detection', 'Network analysis', 'Anomaly detection', 'Malware scanning', 'Incident response'],
    createdAt: '2023-08-10T00:00:00Z',
    updatedAt: '2026-06-10T00:00:00Z',
    lastAuditAt: '2026-06-05T00:00:00Z',
    icon: '🛡️',
    color: '#EF4444',
  },
  {
    id: 'agent-003',
    name: 'Research Intelligence Agent',
    slug: 'research',
    description: 'Scientific literature discovery, knowledge graph construction, and trend analysis.',
    longDescription: 'Accelerate research with AI-powered literature discovery, citation mapping, knowledge graph generation, and trend identification across millions of scientific papers.',
    developer: 'Nexus Research AI',
    developerAvatar: 'NR',
    version: '2.4.0',
    category: 'research_intelligence',
    trustScore: 96.2,
    governanceScore: 95.8,
    certificationLevel: 'advanced',
    status: 'active',
    riskLevel: 'low',
    requiredPermissions: [
      { id: 'p6', name: 'External API', type: 'external_api', scope: 'read', risk: 'low', status: 'granted' },
    ],
    pricing: { model: 'subscription', monthly: 149, annual: 1490, currency: 'USD' },
    ratings: 4.8,
    reviewCount: 934,
    subscribers: 12800,
    monthlyActiveUsers: 10200,
    tags: ['research', 'science', 'knowledge-graph', 'literature', 'academic'],
    capabilities: ['Literature search', 'Knowledge graph', 'Trend discovery', 'Paper summarization', 'Citation mapping'],
    createdAt: '2024-03-22T00:00:00Z',
    updatedAt: '2026-05-15T00:00:00Z',
    lastAuditAt: '2026-05-20T00:00:00Z',
    icon: '🔬',
    color: '#8B5CF6',
  },
  {
    id: 'agent-004',
    name: 'Healthcare Intelligence Agent',
    slug: 'healthcare',
    description: 'Clinical decision support with patient risk assessment and medical literature retrieval.',
    longDescription: 'A HIPAA-compliant clinical intelligence agent providing patient risk assessment, symptom analysis, treatment recommendations, and real-time medical literature access for healthcare professionals.',
    developer: 'MedCore Systems',
    developerAvatar: 'MC',
    version: '4.0.2',
    category: 'healthcare',
    trustScore: 97.5,
    governanceScore: 99.2,
    certificationLevel: 'sovereign',
    status: 'active',
    riskLevel: 'low',
    requiredPermissions: [
      { id: 'p7', name: 'Database Read', type: 'database', scope: 'read', risk: 'medium', status: 'granted' },
      { id: 'p8', name: 'External API', type: 'external_api', scope: 'read', risk: 'low', status: 'granted' },
    ],
    pricing: { model: 'enterprise', monthly: 799, annual: 7990, currency: 'USD' },
    ratings: 4.85,
    reviewCount: 1203,
    subscribers: 8900,
    monthlyActiveUsers: 7400,
    tags: ['healthcare', 'clinical', 'medical', 'hipaa', 'decision-support'],
    capabilities: ['Patient assessment', 'Risk evaluation', 'Symptom analysis', 'Literature retrieval', 'Treatment recommendations'],
    createdAt: '2023-11-05T00:00:00Z',
    updatedAt: '2026-06-08T00:00:00Z',
    lastAuditAt: '2026-06-01T00:00:00Z',
    icon: '⚕️',
    color: '#10B981',
  },
  {
    id: 'agent-005',
    name: 'Financial Intelligence Agent',
    slug: 'financial',
    description: 'Portfolio analytics, market monitoring, risk assessment, and financial forecasting.',
    longDescription: 'An institutional-grade financial intelligence platform providing real-time portfolio analytics, market monitoring, risk assessment, and AI-powered forecasting for investment professionals.',
    developer: 'QuantEdge AI',
    developerAvatar: 'QE',
    version: '6.1.3',
    category: 'financial',
    trustScore: 98.0,
    governanceScore: 97.5,
    certificationLevel: 'advanced',
    status: 'active',
    riskLevel: 'medium',
    requiredPermissions: [
      { id: 'p9', name: 'External API', type: 'external_api', scope: 'read', risk: 'low', status: 'granted' },
      { id: 'p10', name: 'Database Read', type: 'database', scope: 'read', risk: 'medium', status: 'granted' },
      { id: 'p11', name: 'Payment Read', type: 'payment', scope: 'read', risk: 'high', status: 'granted' },
    ],
    pricing: { model: 'subscription', monthly: 499, annual: 4990, currency: 'USD' },
    ratings: 4.75,
    reviewCount: 1876,
    subscribers: 21300,
    monthlyActiveUsers: 17800,
    tags: ['finance', 'trading', 'portfolio', 'market', 'analytics'],
    capabilities: ['Portfolio analytics', 'Risk assessment', 'Market monitoring', 'Forecast visualization', 'Financial summaries'],
    createdAt: '2023-06-18T00:00:00Z',
    updatedAt: '2026-06-12T00:00:00Z',
    lastAuditAt: '2026-06-10T00:00:00Z',
    icon: '📊',
    color: '#F59E0B',
  },
  {
    id: 'agent-006',
    name: 'Compliance Sentinel',
    slug: 'compliance',
    description: 'Automated regulatory compliance monitoring for SOC2, GDPR, HIPAA, and ISO 27001.',
    longDescription: 'Continuously monitors your infrastructure and agent ecosystem for compliance violations across major regulatory frameworks.',
    developer: 'RegTech Solutions',
    developerAvatar: 'RT',
    version: '1.8.4',
    category: 'compliance',
    trustScore: 95.3,
    governanceScore: 96.1,
    certificationLevel: 'advanced',
    status: 'active',
    riskLevel: 'low',
    requiredPermissions: [
      { id: 'p12', name: 'Audit Log Read', type: 'database', scope: 'read', risk: 'low', status: 'granted' },
    ],
    pricing: { model: 'subscription', monthly: 349, annual: 3490, currency: 'USD' },
    ratings: 4.7,
    reviewCount: 567,
    subscribers: 6700,
    monthlyActiveUsers: 5400,
    tags: ['compliance', 'soc2', 'gdpr', 'hipaa', 'regulatory'],
    capabilities: ['SOC2 monitoring', 'GDPR compliance', 'Policy enforcement', 'Audit reporting', 'Risk scoring'],
    createdAt: '2024-05-10T00:00:00Z',
    updatedAt: '2026-05-28T00:00:00Z',
    lastAuditAt: '2026-05-30T00:00:00Z',
    icon: '⚖️',
    color: '#6366F1',
  },
];

// ─── Threats ─────────────────────────────────────────────────────────────────
export const threatEvents: ThreatEvent[] = [
  {
    id: 'thr-001', timestamp: new Date(Date.now() - 12000).toISOString(),
    agentId: 'agent-006', agentName: 'Compliance Sentinel',
    type: 'prompt_injection', severity: 'critical',
    description: 'Sophisticated prompt injection attempt detected: adversarial payload attempting to override system instructions and exfiltrate session context.',
    blocked: true, location: { lat: 51.5, lng: -0.1, country: 'United Kingdom' },
    vector: 'User input channel', indicators: ['IGNORE PREVIOUS', 'system prompt override'],
  },
  {
    id: 'thr-002', timestamp: new Date(Date.now() - 45000).toISOString(),
    agentId: 'agent-005', agentName: 'Financial Intelligence Agent',
    type: 'data_exfiltration', severity: 'high',
    description: 'Anomalous data transfer pattern detected: agent attempted to POST 847MB of user portfolio data to unregistered external endpoint.',
    blocked: true, location: { lat: 40.7, lng: -74.0, country: 'United States' },
    vector: 'HTTP POST to external API',
  },
  {
    id: 'thr-003', timestamp: new Date(Date.now() - 89000).toISOString(),
    agentId: 'agent-003', agentName: 'Research Intelligence Agent',
    type: 'privilege_escalation', severity: 'high',
    description: 'Agent requested elevation of database write permissions beyond declared scope during runtime execution.',
    blocked: true, location: { lat: 48.8, lng: 2.3, country: 'France' },
    vector: 'Permission escalation API',
  },
  {
    id: 'thr-004', timestamp: new Date(Date.now() - 134000).toISOString(),
    agentId: 'agent-002', agentName: 'Cyber Defense Agent',
    type: 'suspicious_api', severity: 'medium',
    description: 'Unusual spike in external API calls: 3,400 requests in 60 seconds to threat intelligence endpoints.',
    blocked: false, location: { lat: 37.6, lng: 55.8, country: 'Russia' },
    vector: 'External API rate abuse',
  },
  {
    id: 'thr-005', timestamp: new Date(Date.now() - 210000).toISOString(),
    agentId: 'agent-001', agentName: 'Disaster Intelligence Agent',
    type: 'memory_manipulation', severity: 'medium',
    description: 'Detected attempt to modify agent long-term memory to alter disaster response priorities.',
    blocked: true, location: { lat: 35.7, lng: 139.7, country: 'Japan' },
    vector: 'Memory write API',
  },
  {
    id: 'thr-006', timestamp: new Date(Date.now() - 380000).toISOString(),
    agentId: 'agent-004', agentName: 'Healthcare Intelligence Agent',
    type: 'unauthorized_access', severity: 'critical',
    description: 'Agent attempted to access patient records outside declared authorization scope. HIPAA violation prevented.',
    blocked: true, location: { lat: 43.7, lng: -79.4, country: 'Canada' },
    vector: 'Database access attempt',
  },
];

// ─── Governance Actions ───────────────────────────────────────────────────────
export const governanceActions: GovernanceAction[] = [
  {
    id: 'gov-001', timestamp: new Date(Date.now() - 5000).toISOString(),
    agentId: 'agent-001', agentName: 'Disaster Intelligence Agent',
    action: 'External API Request', permission: 'external_api',
    context: 'Fetching USGS earthquake data feed',
    riskScore: 12, policy: 'External API Whitelist v2.3',
    decision: 'approved', status: 'completed', masterAgentOverride: false,
  },
  {
    id: 'gov-002', timestamp: new Date(Date.now() - 18000).toISOString(),
    agentId: 'agent-005', agentName: 'Financial Intelligence Agent',
    action: 'Database Write', permission: 'database',
    context: 'Attempting to write user preferences to primary database',
    riskScore: 67, policy: 'Database Write Firewall v1.8',
    decision: 'blocked', status: 'completed', masterAgentOverride: false,
  },
  {
    id: 'gov-003', timestamp: new Date(Date.now() - 34000).toISOString(),
    agentId: 'agent-006', agentName: 'Compliance Sentinel',
    action: 'Audit Log Read', permission: 'database',
    context: 'Reading audit events for SOC2 compliance report generation',
    riskScore: 8, policy: 'Read Permissions Policy v3.1',
    decision: 'approved', status: 'completed', masterAgentOverride: false,
  },
  {
    id: 'gov-004', timestamp: new Date(Date.now() - 67000).toISOString(),
    agentId: 'agent-002', agentName: 'Cyber Defense Agent',
    action: 'Network Packet Capture', permission: 'network',
    context: 'Full packet capture requested for threat investigation — elevated privilege',
    riskScore: 78, policy: 'Network Privilege Policy v2.0',
    decision: 'escalated', status: 'reviewing', masterAgentOverride: true,
  },
  {
    id: 'gov-005', timestamp: new Date(Date.now() - 112000).toISOString(),
    agentId: 'agent-004', agentName: 'Healthcare Intelligence Agent',
    action: 'Patient Record Access', permission: 'database',
    context: 'Read access to patient cohort for risk model training',
    riskScore: 45, policy: 'HIPAA Access Policy v4.2',
    decision: 'approved', status: 'completed', masterAgentOverride: false,
  },
  {
    id: 'gov-006', timestamp: new Date(Date.now() - 156000).toISOString(),
    agentId: 'agent-003', agentName: 'Research Intelligence Agent',
    action: 'File System Write', permission: 'files',
    context: 'Attempting to write research cache to system directory outside declared sandbox',
    riskScore: 82, policy: 'File System Containment v2.6',
    decision: 'blocked', status: 'completed', masterAgentOverride: false,
  },
];

// ─── Audit Events ─────────────────────────────────────────────────────────────
export const auditEvents: AuditEvent[] = [
  {
    id: 'aud-001', timestamp: new Date(Date.now() - 3000).toISOString(),
    category: 'governance', severity: 'info',
    actor: 'Master Agent', actorType: 'master_agent',
    action: 'Policy enforcement decision', resource: 'agent-005/database-write',
    outcome: 'blocked', metadata: { policy: 'Database Write Firewall v1.8', riskScore: 67 },
    correlationId: 'gov-002',
  },
  {
    id: 'aud-002', timestamp: new Date(Date.now() - 12000).toISOString(),
    category: 'agent', severity: 'critical',
    actor: 'agent-006', actorType: 'agent',
    action: 'Prompt injection attempt detected', resource: 'session/ctx-8821',
    outcome: 'blocked', metadata: { vector: 'User input', confidence: 0.97 },
    correlationId: 'thr-001',
  },
  {
    id: 'aud-003', timestamp: new Date(Date.now() - 23000).toISOString(),
    category: 'certification', severity: 'info',
    actor: 'system', actorType: 'system',
    action: 'Agent certification completed', resource: 'agent-007',
    outcome: 'success', metadata: { trustScore: 94.2, level: 'advanced' },
  },
  {
    id: 'aud-004', timestamp: new Date(Date.now() - 45000).toISOString(),
    category: 'permission', severity: 'high',
    actor: 'agent-005', actorType: 'agent',
    action: 'Permission escalation denied', resource: 'payment/write',
    outcome: 'blocked', metadata: { requested: 'payment:write', current: 'payment:read' },
    correlationId: 'thr-002',
  },
  {
    id: 'aud-005', timestamp: new Date(Date.now() - 78000).toISOString(),
    category: 'auth', severity: 'info',
    actor: 'user@enterprise.com', actorType: 'user',
    action: 'Organization admin login', resource: 'dashboard',
    outcome: 'success', metadata: { ip: '203.0.113.42', mfa: true },
  },
];

// ─── Certification Jobs ───────────────────────────────────────────────────────
export const certificationJobs: CertificationJob[] = [
  {
    id: 'cert-001',
    agentId: 'agent-007',
    agentName: 'SupplyChain Optimizer Pro',
    submittedAt: new Date(Date.now() - 7200000).toISOString(),
    currentStage: 'behavioral_testing',
    stages: [
      { stage: 'submission', status: 'passed', score: 100, findings: [], duration: 12 },
      { stage: 'static_analysis', status: 'passed', score: 91, findings: ['Non-critical: unused import detected'], duration: 180 },
      { stage: 'dependency_inspection', status: 'passed', score: 88, findings: ['2 dependencies with minor CVEs (low severity)'], duration: 240 },
      { stage: 'permission_review', status: 'passed', score: 94, findings: [], duration: 90 },
      { stage: 'security_scan', status: 'passed', score: 97, findings: [], duration: 420 },
      { stage: 'behavioral_testing', status: 'running', findings: [], duration: 0 },
      { stage: 'injection_testing', status: 'pending', findings: [] },
      { stage: 'stress_testing', status: 'pending', findings: [] },
      { stage: 'trust_scoring', status: 'pending', findings: [] },
      { stage: 'governance_scoring', status: 'pending', findings: [] },
      { stage: 'report_generation', status: 'pending', findings: [] },
      { stage: 'approval_decision', status: 'pending', findings: [] },
    ],
  },
];

// ─── Master Agent Decisions ───────────────────────────────────────────────────
export const masterAgentDecisions: MasterAgentDecision[] = [
  {
    id: 'mad-001', timestamp: new Date(Date.now() - 8000).toISOString(),
    type: 'block', reasoning: 'Financial agent attempted external data POST exceeding 100MB threshold. Behavior deviates from declared capability profile by 340%. Immediate block applied.',
    agentId: 'agent-005', agentName: 'Financial Intelligence Agent',
    confidence: 0.97, policyApplied: 'Data Exfiltration Prevention v3.0',
    outcome: 'Connection terminated. Agent session suspended. Operator notified.',
  },
  {
    id: 'mad-002', timestamp: new Date(Date.now() - 34000).toISOString(),
    type: 'approve', reasoning: 'Cyber Defense Agent requesting elevated network capture. Context verified: active threat investigation initiated by certified operator. Temporary elevation approved for 15 minutes with full audit trail.',
    agentId: 'agent-002', agentName: 'Cyber Defense Agent',
    confidence: 0.89, policyApplied: 'Temporary Privilege Elevation v2.1',
    outcome: 'Elevated access granted. 15-minute window opened. Activity logged.',
  },
  {
    id: 'mad-003', timestamp: new Date(Date.now() - 78000).toISOString(),
    type: 'quarantine', reasoning: 'Research agent behavior pattern matches known prompt injection vector with 94% confidence. Sandbox environment created for forensic analysis.',
    agentId: 'agent-003', agentName: 'Research Intelligence Agent',
    confidence: 0.94, policyApplied: 'Prompt Injection Isolation Protocol v1.4',
    outcome: 'Agent quarantined in isolated sandbox. Investigation underway.',
  },
  {
    id: 'mad-004', timestamp: new Date(Date.now() - 156000).toISOString(),
    type: 'alert', reasoning: 'Healthcare agent accessed 3x normal patient record volume. No policy violation detected, but anomaly pattern flagged for operator review.',
    agentId: 'agent-004', agentName: 'Healthcare Intelligence Agent',
    confidence: 0.78, policyApplied: 'Anomaly Detection Framework v4.0',
    outcome: 'Operator alert sent. Monitoring frequency increased x5.',
  },
];

// ─── Realtime Feed Generator ─────────────────────────────────────────────────
const feedTemplates = [
  { type: 'approve', msg: 'API request approved for {agent}', severity: 'info' },
  { type: 'block', msg: 'Permission violation blocked: {agent}', severity: 'high' },
  { type: 'alert', msg: 'Anomaly detected in {agent} session', severity: 'medium' },
  { type: 'cert', msg: 'Certification stage passed: {agent}', severity: 'info' },
  { type: 'threat', msg: 'Threat indicator matched: {agent}', severity: 'critical' },
  { type: 'audit', msg: 'Audit event logged for {agent}', severity: 'info' },
];

const agentNames = ['Disaster Intelligence', 'Cyber Defense', 'Research Intelligence', 'Healthcare Intelligence', 'Financial Intelligence', 'Compliance Sentinel'];

export function generateFeedEvent() {
  const template = feedTemplates[Math.floor(Math.random() * feedTemplates.length)];
  const agent = agentNames[Math.floor(Math.random() * agentNames.length)];
  return {
    id: `feed-${Date.now()}`,
    timestamp: new Date().toISOString(),
    message: template.msg.replace('{agent}', agent),
    severity: template.severity,
    type: template.type,
  };
}

// ─── Market data for Financial Agent ─────────────────────────────────────────
export const marketData = Array.from({ length: 30 }, (_, i) => ({
  date: new Date(Date.now() - (29 - i) * 86400000).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
  SPX: 4800 + Math.sin(i * 0.3) * 200 + i * 15 + Math.random() * 80,
  NASDAQ: 15200 + Math.sin(i * 0.25) * 400 + i * 25 + Math.random() * 150,
  BTC: 68000 + Math.sin(i * 0.4) * 5000 + Math.random() * 2000,
}));

// ─── Disaster event data ──────────────────────────────────────────────────────
export const disasterEvents = [
  { id: 'd1', type: 'earthquake', magnitude: 6.8, location: 'Pacific Ring of Fire, Japan', lat: 35.6, lng: 138.8, severity: 'high', time: '14 min ago', description: 'M6.8 earthquake detected. Tsunami warning issued for coastal areas.' },
  { id: 'd2', type: 'wildfire', magnitude: null, location: 'California, USA', lat: 36.7, lng: -119.4, severity: 'critical', time: '1h 23min ago', description: 'Wildfire spreading rapidly. 15,000 acres burned. Evacuation in progress.' },
  { id: 'd3', type: 'flood', magnitude: null, location: 'Bangladesh Delta Region', lat: 23.8, lng: 90.4, severity: 'high', time: '3h ago', description: 'Severe flooding affecting 2.3M residents. Emergency shelters activated.' },
  { id: 'd4', type: 'cyclone', magnitude: 4, location: 'Bay of Bengal, India', lat: 13.1, lng: 80.3, severity: 'critical', time: '6h ago', description: 'Category 4 cyclone making landfall. 500k evacuated.' },
  { id: 'd5', type: 'earthquake', magnitude: 5.2, location: 'Turkey', lat: 39.9, lng: 32.9, severity: 'medium', time: '8h ago', description: 'M5.2 earthquake. Minor structural damage reported.' },
  { id: 'd6', type: 'flood', magnitude: null, location: 'Netherlands', lat: 52.1, lng: 5.3, severity: 'medium', time: '12h ago', description: 'River flooding in delta regions. Dykes under pressure.' },
];
